%%%======================     名稱定義列表  =============================%%%
%%%
%%%  map:   是一地圖矩陣，用於顯示目前真實地圖的情況。
%%%  distanceFromStart:    是一地圖矩陣，記錄起始點到各點的最短距離。   
%%%  parent:    是一地圖矩陣，記錄起始點到被探索的所有節點的路徑形勢。
%%%
%%%
%%%
%%%
%%%=====================================================================%%%
%%%======================    Edition List  =============================%%%
%%% 2017/07/24 :
%%%     1. Normal simulation of Dijkstra Algorithm.
%%%        
%%%     by Stud.Pang
%%%
%%%2017/08/05
%%%     1. GUI Design: Apply ginput(Matlab) in initial map setup. (Haven't Complete)  
%%%     
%%%     by Stud.Pang
%%%
%%%2017/08/07
%%%     1. GUI Design: Apply image('ButtonDownFcn',@Map_setup)
%%%     2. GUI Design: Apply uicontrol:ButtonStart ('Callback',@Optimization_Path)
%%%     3. GUI Design: Apply uicontrol:ButtonClear('Callback',@Clear_Path)
%%%     4. GUI Design: Information and Title
%%%
%%%     by Stud.Pang
%%%
%%%2017/08/08
%%%     1. Combination with real grid-map ( 5892m ). (Haven't Complete)
%%%
%%%     by Stud.Pang
%%%
%%%2017/08/09
%%%     1. Combination with real grid-map ( 5892m ). 
%%%     2. Combine all uicontrol data with structure type. (ButtonStart done! )
%%%
%%%     by Stud.Pang
%%%
%%%2017/08/10
%%%     1. Combination with real grid-map ( 5892m ). 
%%%     2. Combine all uicontrol data with structure type. (All done! )
%%%
%%%     by Stud.Pang
%%%
%%%2017/08/15
%%%     1. Implementation of impyramid to reduce the calculation time. 
%%%
%%%
%%%2017/09/20
%%%     5. GUI Design: Apply uicontrol: Popup
%%%
%%%     by Stud.Pang
%%%=====================================================================%%%
clear all;close all;clc;

%%=== Setting Image Color to Define Map %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cmap = [ 0        0       0; ... % 1 - black - clear cell
         1        1       1; ... % 2 - white - obstacle
         0.9804   0.4     0.4; ... % 3 - red - visited
         0.8      0.8     1; ... % 4 - light purple - on list
         0        1       0; ... % 5 - green - start
         1        1       0; ... % 6 - yellow - destination
         0.9686   0.8039  0.8039; ...% 7 - pink - dangerous zone
         0.8039   0.9804  0.9804;...% 8 - light green - save zone
         0        0       1;...% 9 - blue - final path
         0.412    0.412   0.412;...% 10 - grey - dynamic obstacle
         1        0.647   0.31]; % 11 - orange chocolate - boundary detection
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%%=== Creating A GUI Figure %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Fig = figure();
% test = [1 2 3 5 6 4 8];
% parameters = struct('test',test);
% set(Fig,'UserData',parameters);
set(Fig, 'Name', 'Path Scoring Simulator', ... 
    'NumberTitle', 'off', 'OuterPosition',get(0,'ScreenSize'), 'Resize', 'off');

colormap(cmap); %%... setting the color theme of the image corresponding to the meaning of each color occupancy
map = 2*ones(10); %%... setting the start default map 
map_init = 2*ones(10);%%... for reset button (@Reset_Path), keeping original map and clear all setting
map_current = 2*ones(10);%%... for clear button (@Clear_Path), keeping the start and destination node
map_color_value = 3;
parameters.map_init = map_init;
parameters.map_current = map_current;
parameters.map_color_value = map_color_value;
Fig.UserData = parameters;


%%=== Creating an Display Axes on Figure %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
AXES = axes('Parent', Fig, ...
    'Units','normalized',...
    'Position',[0.045 0.045 0.512 0.946]);



%%=== Display Result Using Image %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Img = image(map,'Parent', AXES,'XData',1.5,'YData',1.5); %%... to get mouse position at image area (@Map_setup)
grid on;   
axis image; 
set(Img,'ButtonDownFcn',@Map_Setup);
% set(Img,'CData',map_current);
set(AXES,'FontSize',18);
c = uicontextmenu;
d = uicontextmenu;
% Assign the uicontextmenu to object
Fig.UIContextMenu = d;
Img.UIContextMenu = c;
% Create child menu items for the uicontextmenu
m1 = uimenu(c,'Label','Green','Callback',@Map_Setup_Rclick);
m2 = uimenu(c,'Label','Yellow','Callback',@Map_Setup_Rclick);
m3 = uimenu(c,'Label','White','Callback',@Map_Setup_Rclick);
m4 = uimenu(c,'Label','Dynamic Obstacle','Callback',@Map_Setup_Rclick);
m5 = uimenu(c,'Label','Static Obstacle','Callback',@Map_Setup_Rclick);
m6 = uimenu(d,'Label','Green','Callback',@Map_Setup_Rclick_Fig);
m7 = uimenu(d,'Label','Yellow','Callback',@Map_Setup_Rclick_Fig);
m8 = uimenu(d,'Label','White','Callback',@Map_Setup_Rclick_Fig);
m9 = uimenu(d,'Label','Dynamic Obstacle','Callback',@Map_Setup_Rclick_Fig);
m10 = uimenu(d,'Label','Static Obstacle','Callback',@Map_Setup_Rclick_Fig);
% Arrow = patch(0,0,'g','EdgeColor','g',...
%                 'FaceAlpha', 1, 'LineWidth', 1);




%%=== Simulator Object %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Title = uicontrol('Parent',Fig,'Style', 'text',...
    'String','Path Scoring Simulator',... 
    'FontSize',25,'Units','normalized',...
    'Position', [0.683 0.931 0.176 0.051]);



%%=== Browse Map from PC Path %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Browse_Button = uicontrol('Parent',Fig,'Style','pushbutton',... %%... button for browse map image (@Browse_Image)
    'String','Browse Image', ...
    'Units','normalized','FontSize',10,...
    'Position',[0.841 0.735 0.115 0.032],'Visible','on' ,...
    'CallBack',@Browse_Image);  
Browse_Frame = uicontrol('Parent',Fig,'Style','frame',... %%... for decoration
    'Units','normalized',...
    'Position', [0.841 0.771 0.114 0.078]);
Browse_Info = uicontrol('Parent',Fig,'Style','text',... %%... showing map information
        'String',sprintf('\nDemo Kit 10x10'),'BackgroundColor','White',...
        'Units','normalized','HorizontalAlignment','center',...
        'FontSize',15,...
        'Position', [0.842 0.775 0.111 0.07]);
Browse_Text = uicontrol('Parent',Fig,'Style','text',... %%... legend of browse info
    'String','Current Map :','FontSize',12,...
    'Units','normalized',...
    'Position', [0.84 0.853 0.052 0.021]);    
    


%%=== Path Scoring Specification %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Specification_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Specification :','FontSize',12,...
    'Units','normalized',...
    'Position', [0.811 0.688 0.059 0.021]);
Specification_Frame = uicontrol('Parent',Fig,'Style','frame',...
   'Units','normalized',...
   'Position', [0.811 0.151 0.178 0.532]);



%%=== Step 1 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Step_1_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Step 1','FontSize',15,...
    'Units','normalized',...
    'Position', [0.813 0.656 0.035 0.025]);
%%=== Dangerous Zone Range %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Dangerous_Zone_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Dangerous Zone Pixel','FontSize',12,...
    'Units','normalized',...
    'Position', [0.816 0.623 0.095 0.021]);
Dangerous_Zone_Edit = uicontrol('Parent',Fig,'Style', 'edit',... %%... select demo kit plain popup (@Demo_kit)
    'FontSize',10,...
    'Units','normalized',...
    'Position',[0.943 0.621 0.043 0.027],'Visible','on');
%%=== Save Zone Range %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Save_Zone_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Save Zone Pixel','FontSize',12,...
    'Units','normalized',...
    'Position', [0.822 0.58 0.061 0.021]);
Save_Zone_Edit = uicontrol('Parent',Fig,'Style', 'edit',... %%... select demo kit plain popup (@Demo_kit)
    'FontSize',10,...
    'Units','normalized',...
    'Position',[0.943 0.577 0.043 0.027],'Visible','on'); 
%%===Boundary Detection %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Boundary_Detection_Check = uicontrol('Parent',Fig,'Style','check',...
    'Units','normalized',...
    'Position',[0.9 0.544 0.009 0.021]);
Boundary_Detection_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Boundary Detection','FontSize',12,...
    'Units','normalized',...
    'Position', [0.912 0.543 0.073 0.022]);
Refresh_Button = uicontrol('Parent',Fig,'Style','pushbutton',... %%... clear the scoring result with all initial setting (@Clear_Path)
    'String','Refresh', ...
    'Units','normalized','FontSize',10,...
    'Position',[0.941 0.518 0.045 0.021],'Visible','on' ,...
    'Callback',@Browse_Image);



%%=== Step 2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Step_2_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Step 2','FontSize',15,...
    'Units','normalized',...
    'Position', [0.813 0.485 0.035 0.025]);
%%=== Demonstration Kit Setting %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Demo_Kit_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Demo Kit Dimension','FontSize',12,...
    'Units','normalized',...
    'Position', [0.817 0.452 0.048 0.021]);
Demo_Kit_Popup = uicontrol('Parent',Fig,'Style', 'popup',... %%... select demo kit plain popup (@Demo_kit)
    'String',{'10x10','20x20','30x30','50x50','100x100','500x500'},'FontSize',10,...
    'Units','normalized',...
    'Position',[0.907 0.450 0.079 0.027],'Visible','on' ,...
    'CallBack',@Demo_Kit);   
%%=== Path Scoring Algorithm Selection %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Algorithm_Selection_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Algorithm Selection','FontSize',12,...
    'Units','normalized',...
    'Position', [0.819 0.402 0.077 0.021]);
Algorithm_Selection = uicontrol('Parent',Fig,'Style', 'popup',... %%... select algorithm popup
    'String', {'Dijkstra','A*','A* Heuristic','Greedy Appoarch','Heuristic Weight'},'FontSize',10,...
    'Units','normalized',...
    'Position', [0.907 0.406  0.079 0.02]);
% %%=== Map Initial Setup (Assign Start Node, Destination Node, Obstacle) %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Map_Color_Setup_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
%     'String','Map Color Setup','FontSize',12,...
%     'Units','normalized',...
%     'Position', [0.82 0.347 0.065 0.026]);
% Map_Color_Setup = uicontrol('Parent',Fig,'Style', 'popup',... %%... select occupancy color
%     'String', {'Green','Yellow','White','Dynamic Obstacle','Static Obstacle'},'FontSize',10,...
%     'Units','normalized',...
%     'Position', [0.907 0.348 0.079 0.028]);
%%=== Mission Selection %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Mission_Text = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','Mission','FontSize',12,...
    'Units','normalized',...
    'Enable','on',...
    'Position', [0.82 0.347 0.03 0.026]);
Mission_Selection = uicontrol('Parent',Fig,'Style', 'popup',... %%... select occupancy color
    'String', {'Path Planning','Wall Following by Zone','Wall Following by Closest Point','Peeling'},'FontSize',10,...
    'Units','normalized',...
    'Enable','on',...
    'Position', [0.907 0.348 0.079 0.028]);
%%=== Exploring Direction %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Exploring_Direction_Check = uicontrol('Parent',Fig,'Style','check',...
    'Units','normalized',...
    'Position',[0.933 0.154 0.01 0.021]);
Exploring_Direction_Text1 = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','8 directions','FontSize',12,...
    'Units','normalized',...
    'Position', [0.943 0.157 0.044 0.018]);
Exploring_Direction_Text2 = uicontrol('Parent',Fig,'Style','text',... %%... for information
    'String','(dafault as 4)','FontSize',10,...
    'Units','normalized',...
    'Enable','off',...
    'Position', [0.944 0.177 0.042 0.017]);
Self_Clicking_Map = uicontrol('Parent',Fig,'Style','pushbutton',... %%... clear the scoring result with all initial setting (@Clear_Path)
    'String','Comfirm Map', ...
    'Units','normalized','FontSize',10,...
    'Position',[0.941 0.244 0.045 0.021],'Visible','on' ,...
    'Callback',@Self_Map_Comfirm);




%%=== Algorithm Trigger %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Button_Start=uicontrol('Parent',Fig,'Style','pushbutton',... %%... start calculating with specification above(@Drawing_path)
    'String','Path Scoring', ...
    'Units','normalized','FontSize',20,...
    'Position',[0.82 0.082 0.164 0.061],'Visible','on' ,...
    'Callback',@Drawing_Path);
Button_Clear=uicontrol('Parent',Fig,'Style','pushbutton',... %%... clear the scoring result without clear initial setting (@Clear_Path)
    'String','Clear Path', ...
    'Units','normalized','FontSize',15,...
    'Position',[0.82 0.033 0.079 0.045],'Visible','on' ,...
    'Enable','off',...
    'Callback',@Clear_Path);
Button_Reset=uicontrol('Parent',Fig,'Style','pushbutton',... %%... clear the scoring result with all initial setting (@Clear_Path)
    'String','Reset All Map', ...
    'Units','normalized','FontSize',15,...
    'Position',[0.903 0.033 0.08 0.045],'Visible','on' ,...
    'Callback',@Reset_Path);



%%=== Result Information Panel %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Calculation_Info_Frame = uicontrol('Parent',Fig,'Style','frame',...
   'Units','normalized',...
   'Position', [0.563 0.622 0.232 0.214]);
Calculation_Info = uicontrol('Parent',Fig,'Style','text',...
        'String',sprintf(''),...
        'Units','normalized','HorizontalAlignment','left',...
        'FontSize',15,...
        'Position', [0.572 0.668 0.214 0.121]);
Calculation_Info_Title = uicontrol('Parent',Fig, 'Style', 'text',...
    'String',sprintf('Path Scoring Result'),... 
    'FontSize',15,'Units','normalized',...
    'Position', [0.562 0.843 0.094 0.027]);
Force_Stop = uicontrol('Parent',Fig,'Style','pushbutton',... %%... to break the scoring algorithm when calculating
    'String','Force Stop', ...
    'Units','normalized','FontSize',15,...
    'Position',[0.683 0.565 0.113 0.052],'Visible','on',...
    'Enable','off',...
    'Callback', @(h_obj, ~) set(h_obj, 'Enable', 'off') );



%%=== Map Color Information %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Information_Frame = uicontrol('Parent',Fig,'Style','frame',...
   'Units','normalized',...
   'Position', [0.563 0.323 0.231 0.153]);
Information = uicontrol('Parent',Fig,'Style', 'text',...
    'String',sprintf('White=Empty Cell      Black=Obstacle      Red=Visited\n\nBlue=Final Path      Green=Start      Yellow=Destination\n\nPink=Dangerous Zone      Light Blue=Save Zone\n\nLight Purple=On List'),... 
    'FontSize',12,'Units','normalized','HorizontalAlignment','left',...
    'Position', [0.577 0.327 0.212 0.137]);
Information_Title = uicontrol('Parent',Fig, 'Style', 'text',...
    'String',sprintf('Map Cell Color Defination'),... 
    'FontSize',15,'Units','normalized',...
    'Position', [0.564 0.482 0.122 0.027]);



%%=== Current Click Color %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Current_Color_Title = uicontrol('Parent',Fig, 'Style', 'text',...
    'String',sprintf('Current Clicking Node Status'),... 
    'FontSize',15,'Units','normalized',...
    'Position', [0.564 0.241 0.146 0.027]);
Current_Color_Frame = uicontrol('Parent',Fig,'Style','frame',...
   'Units','normalized',...
   'Position', [0.563 0.156 0.231 0.078]);
Current_Color_Information = uicontrol('Parent',Fig,'Style', 'text',...
    'String',sprintf('White Node'),... 
    'FontSize',20,'Units','normalized','HorizontalAlignment','center',...
    'Position', [0.599 0.179 0.153 0.036]);
Tips = uicontrol('Parent',Fig,'Style', 'text',...
    'String',sprintf('* Tips: right click empty area to select clicking color'),... 
    'FontSize',10,'Units','normalized','HorizontalAlignment','center',...
    'Enable','off','Position', [0.558 0.131 0.168 0.022]);




%%=== Showing the Direction of Optimize Path %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Path_Arrow = patch('Parent',AXES,'XData',[],'YData',[]);

    

handles = struct('Fig',Fig,...
                 'AXES',AXES,...
                 'Img',Img,... %%... UserData reserved by handles
                 'Button_Start',Button_Start,...             
                 'Button_Clear',Button_Clear,...
                 'Button_Reset',Button_Reset,...
                 'Algorithm_Selection',Algorithm_Selection,...
                 'Mission_Selection',Mission_Selection,...
                 'Calculation_Info',Calculation_Info,...
                 'Browse_Button',Browse_Button,...
                 'Browse_Info',Browse_Info,...
                 'Demo_Kit_Popup',Demo_Kit_Popup,...
                 'Exploring_Direction_Check',Exploring_Direction_Check,...
                 'Force_Stop',Force_Stop,...
                 'Dangerous_Zone_Edit',Dangerous_Zone_Edit,...
                 'Save_Zone_Edit',Save_Zone_Edit,...
                 'Boundary_Detection_Check',Boundary_Detection_Check,... 
                 'Path_Arrow',Path_Arrow,...
                 'm1',m1,'m2',m2,'m3',m3,'m4',m4,'m5',m5,...               %%  'Map_Color_Setup',Map_Color_Setup,...
                 'm6',m6,'m7',m7,'m8',m8,'m9',m9,'m10',m10,...
                 'Current_Color_Information',Current_Color_Information);%%,...
                %%% 'Arrow',Arrow);
                 
                 
                 

set(Img,'UserData',handles); 
set(Browse_Button,'UserData',handles);
set(Refresh_Button,'UserData',handles);
set(Demo_Kit_Popup,'UserData',handles);
set(Button_Start,'UserData',handles);
set(Button_Clear,'UserData',handles);
set(Button_Reset,'UserData',handles);
set(Force_Stop,'UserData',handles);
set(m1,'UserData',handles);
set(m2,'UserData',handles);
set(m3,'UserData',handles);
set(m4,'UserData',handles);
set(m5,'UserData',handles);
set(m6,'UserData',handles);
set(m7,'UserData',handles);
set(m8,'UserData',handles);
set(m9,'UserData',handles);
set(m10,'UserData',handles);
set(Self_Clicking_Map,'UserData',handles);
% set(Map_Color_Setup,'UserData',handles);
% set(Algorithm_Selection,'UserData',handles);
% set(Calculation_Info,'UserData',handles);
% set(Browse_Info,'UserData',handles);
% set(Exploring_Direction_Check,'UserData',handles);

% generate_exe;


